# Generated by Django 4.2.13 on 2024-05-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='nombreAdult',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nombreEnfant',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='telephone',
            field=models.IntegerField(default=0),
        ),
    ]
